ALTER TABLE nodes ADD COLUMN IF NOT EXISTS health_status TEXT NOT NULL DEFAULT 'healthy';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS cpu_usage_pct DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS mem_available_bytes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS disk_free_bytes BIGINT NOT NULL DEFAULT 0;

ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMPTZ;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS idle_suspend_hours INT NOT NULL DEFAULT 0;

ALTER TABLE refresh_sessions ADD COLUMN IF NOT EXISTS fingerprint TEXT NOT NULL DEFAULT '';
