ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS exec_ready BOOLEAN;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS exec_error TEXT NOT NULL DEFAULT '';
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS exec_checked_at TIMESTAMPTZ;
